# Generated by Django 6.0 on 2026-01-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0002_jobseekerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
