# Generated by Django 6.0 on 2026-01-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0003_jobseekerprofile_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
