# Generated by Django 6.0 on 2026-02-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0009_alter_job_options_alter_companyprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')],
                                   default='Pending', max_length=20),
        ),
    ]
