# Generated by Django 6.0 on 2026-03-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(
                choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'),
                         ('Remote', 'Remote')], default='Full Time', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
